"""Reference source - hardcoded dataset for classic/JDM cars."""

REFERENCE_CARS = [
    # Toyota AE86 (1983-1987)
    {
        "make": "Toyota", "model": "Corolla AE86 (Sprinter Trueno)", "year": 1986,
        "trim": "GT-Apex",
        "body_type": "coupe",
        "dimensions": {
            "length": 4.26, "width": 1.63, "height": 1.34,
            "wheelbase": 2.43, "track_width": 1.40, "ground_clearance": 0.15,
            "front_track_m": 1.40, "rear_track_m": 1.40,
            "front_overhang_m": 0.87, "rear_overhang_m": 0.96,
        },
        "engine": {
            "displacement_l": 1.6, "cylinders": 4, "configuration": "I4",
            "aspiration": "NA", "power_hp": 130, "torque_nm": 152,
            "max_rpm": 7600, "idle_rpm": 850, "compression_ratio": 9.4,
            "bore_mm": 81.0, "stroke_mm": 77.0, "valves_per_cylinder": 4,
            "fuel_delivery": "EFI",
        },
        "drivetrain": "rwd",
        "transmission": {"gear_count": 5, "type": "manual", "final_drive": 4.3},
        "brakes": {"front_type": "ventilated_disc", "rear_type": "disc", "front_diameter_mm": 232},
        "suspension": {"front_type": "strut", "rear_type": "four_link"},
        "tires": {"front_size": "185/70R13", "rear_size": "185/70R13", "width_mm": 185, "aspect_ratio": 70, "wheel_diameter_in": 13},
        "aero": {"drag_coefficient": 0.36},
        "weight_kg": 940, "weight_front_pct": 53,
        "fuel_type": "gasoline",
        "performance": {"0_100_km_h": 8.3, "top_speed_km_h": 190, "quarter_mile_s": 16.4, "lateral_g": 0.82},
        "price": {"min_usd": 2500, "max_usd": 35000, "avg_usd": 12000, "note": "original MSRP ~$9k; restored $15k-35k"},
        "eras": "80s,90s", "tags": "jdm,drift,classic,lightweight,affordable",
        "confidence": 0.9, "source": "reference"
    },
    # Mazda MX-5 NA (1989-1997)
    {
        "make": "Mazda", "model": "MX-5 Miata NA", "year": 1990,
        "trim": "1.6",
        "body_type": "roadster",
        "dimensions": {
            "length": 3.97, "width": 1.67, "height": 1.23,
            "wheelbase": 2.27, "track_width": 1.40, "ground_clearance": 0.14,
            "front_track_m": 1.41, "rear_track_m": 1.40,
            "front_overhang_m": 0.78, "rear_overhang_m": 0.92,
        },
        "engine": {
            "displacement_l": 1.6, "cylinders": 4, "configuration": "I4",
            "aspiration": "NA", "power_hp": 116, "torque_nm": 137,
            "max_rpm": 6500, "idle_rpm": 800, "compression_ratio": 9.0,
            "bore_mm": 78.0, "stroke_mm": 83.6, "valves_per_cylinder": 4,
            "fuel_delivery": "EFI",
        },
        "drivetrain": "rwd",
        "transmission": {"gear_count": 5, "type": "manual", "final_drive": 4.1},
        "brakes": {"front_type": "disc", "rear_type": "disc", "front_diameter_mm": 255},
        "suspension": {"front_type": "double_wishbone", "rear_type": "multilink"},
        "tires": {"front_size": "185/60R14", "rear_size": "185/60R14", "width_mm": 185, "aspect_ratio": 60, "wheel_diameter_in": 14},
        "aero": {"drag_coefficient": 0.38},
        "weight_kg": 960, "weight_front_pct": 50,
        "fuel_type": "gasoline",
        "performance": {"0_100_km_h": 9.4, "top_speed_km_h": 183, "quarter_mile_s": 17.1, "lateral_g": 0.87},
        "price": {"min_usd": 2000, "max_usd": 15000, "avg_usd": 7000, "note": "original MSRP ~$14k; good ones $5k-15k"},
        "eras": "90s", "tags": "roadster,lightweight,miata,jdm,affordable,handling",
        "confidence": 0.9, "source": "reference"
    },
    {
        "make": "Mazda", "model": "MX-5 Miata NB", "year": 2000,
        "trim": "1.8",
        "body_type": "roadster",
        "dimensions": {
            "length": 3.95, "width": 1.67, "height": 1.22,
            "wheelbase": 2.29, "track_width": 1.44, "ground_clearance": 0.14,
            "front_track_m": 1.45, "rear_track_m": 1.44,
            "front_overhang_m": 0.78, "rear_overhang_m": 0.88,
        },
        "engine": {
            "displacement_l": 1.8, "cylinders": 4, "configuration": "I4",
            "aspiration": "NA", "power_hp": 146, "torque_nm": 167,
            "max_rpm": 6800, "idle_rpm": 800, "compression_ratio": 10.0,
            "bore_mm": 83.0, "stroke_mm": 85.0, "valves_per_cylinder": 4,
            "fuel_delivery": "EFI",
        },
        "drivetrain": "rwd",
        "transmission": {"gear_count": 5, "type": "manual", "final_drive": 4.1},
        "brakes": {"front_type": "ventilated_disc", "rear_type": "disc", "front_diameter_mm": 258},
        "suspension": {"front_type": "double_wishbone", "rear_type": "multilink"},
        "tires": {"front_size": "195/50R15", "rear_size": "195/50R15", "width_mm": 195, "aspect_ratio": 50, "wheel_diameter_in": 15},
        "aero": {"drag_coefficient": 0.36},
        "weight_kg": 1040, "weight_front_pct": 50,
        "fuel_type": "gasoline",
        "performance": {"0_100_km_h": 7.8, "top_speed_km_h": 200, "quarter_mile_s": 16.0, "lateral_g": 0.91},
        "price": {"min_usd": 3000, "max_usd": 18000, "avg_usd": 9000, "note": "original MSRP ~$21k"},
        "eras": "2000s", "tags": "roadster,lightweight,miata,handling",
        "confidence": 0.9, "source": "reference"
    },
    # Honda Civic EG6 (1992-1995)
    {
        "make": "Honda", "model": "Civic EG6 (Si II)", "year": 1995,
        "trim": "Si II",
        "body_type": "hatchback",
        "dimensions": {
            "length": 4.19, "width": 1.70, "height": 1.35,
            "wheelbase": 2.57, "track_width": 1.47, "ground_clearance": 0.15,
            "front_track_m": 1.47, "rear_track_m": 1.46,
            "front_overhang_m": 0.78, "rear_overhang_m": 0.84,
        },
        "engine": {
            "displacement_l": 1.6, "cylinders": 4, "configuration": "I4",
            "aspiration": "NA", "power_hp": 160, "torque_nm": 150,
            "max_rpm": 7800, "idle_rpm": 800, "compression_ratio": 10.4,
            "bore_mm": 81.0, "stroke_mm": 77.0, "valves_per_cylinder": 4,
            "fuel_delivery": "MPI",
        },
        "drivetrain": "fwd",
        "transmission": {"gear_count": 5, "type": "manual", "final_drive": 4.26},
        "brakes": {"front_type": "disc", "rear_type": "drum", "front_diameter_mm": 262},
        "suspension": {"front_type": "double_wishbone", "rear_type": "double_wishbone"},
        "tires": {"front_size": "185/60R14", "rear_size": "185/60R14", "width_mm": 185, "aspect_ratio": 60, "wheel_diameter_in": 14},
        "aero": {"drag_coefficient": 0.32},
        "weight_kg": 1060, "weight_front_pct": 60,
        "fuel_type": "gasoline",
        "performance": {"0_100_km_h": 7.5, "top_speed_km_h": 210, "quarter_mile_s": 15.8, "lateral_g": 0.85},
        "price": {"min_usd": 3000, "max_usd": 25000, "avg_usd": 12000, "note": "JDM Si II, B16A engine"},
        "eras": "90s", "tags": "jdm,hatchback,hot_hatch,vtec,affordable",
        "confidence": 0.85, "source": "reference"
    },
    # Honda Civic EK9 Type R (1997-2000)
    {
        "make": "Honda", "model": "Civic EK9 (Type R)", "year": 1998,
        "trim": "Type R",
        "body_type": "hatchback",
        "dimensions": {
            "length": 4.18, "width": 1.70, "height": 1.38,
            "wheelbase": 2.62, "track_width": 1.47, "ground_clearance": 0.15,
            "front_track_m": 1.47, "rear_track_m": 1.46,
            "front_overhang_m": 0.76, "rear_overhang_m": 0.80,
        },
        "engine": {
            "displacement_l": 1.6, "cylinders": 4, "configuration": "I4",
            "aspiration": "NA", "power_hp": 185, "torque_nm": 160,
            "max_rpm": 8200, "idle_rpm": 850, "compression_ratio": 10.8,
            "bore_mm": 81.0, "stroke_mm": 77.0, "valves_per_cylinder": 4,
            "fuel_delivery": "MPI",
        },
        "drivetrain": "fwd",
        "transmission": {"gear_count": 5, "type": "manual", "final_drive": 4.79},
        "brakes": {"front_type": "ventilated_disc", "rear_type": "disc", "front_diameter_mm": 282},
        "suspension": {"front_type": "double_wishbone", "rear_type": "double_wishbone"},
        "tires": {"front_size": "195/55R15", "rear_size": "195/55R15", "width_mm": 195, "aspect_ratio": 55, "wheel_diameter_in": 15},
        "aero": {"drag_coefficient": 0.31},
        "weight_kg": 1040, "weight_front_pct": 60,
        "fuel_type": "gasoline",
        "performance": {"0_100_km_h": 6.7, "top_speed_km_h": 215, "quarter_mile_s": 15.2, "lateral_g": 0.93},
        "price": {"min_usd": 8000, "max_usd": 40000, "avg_usd": 20000, "note": "JDM only, B16B engine"},
        "eras": "90s,2000s", "tags": "jdm,type_r,hatchback,hot_hatch,vtec,legend",
        "confidence": 0.85, "source": "reference"
    },
    # Nissan Silvia S13 (1988-1994)
    {
        "make": "Nissan", "model": "Silvia S13", "year": 1989,
        "trim": "Kouki Turbo",
        "body_type": "coupe",
        "dimensions": {
            "length": 4.47, "width": 1.69, "height": 1.29,
            "wheelbase": 2.47, "track_width": 1.46, "ground_clearance": 0.15,
            "front_track_m": 1.46, "rear_track_m": 1.46,
            "front_overhang_m": 0.88, "rear_overhang_m": 1.12,
        },
        "engine": {
            "displacement_l": 1.8, "cylinders": 4, "configuration": "I4",
            "aspiration": "turbo", "power_hp": 177, "torque_nm": 226,
            "max_rpm": 6800, "idle_rpm": 800, "compression_ratio": 8.5,
            "bore_mm": 83.0, "stroke_mm": 83.0, "valves_per_cylinder": 4,
            "fuel_delivery": "MPI", "boost_bar": 0.6,
        },
        "drivetrain": "rwd",
        "transmission": {"gear_count": 5, "type": "manual", "final_drive": 4.08},
        "brakes": {"front_type": "ventilated_disc", "rear_type": "disc", "front_diameter_mm": 257},
        "suspension": {"front_type": "macpherson", "rear_type": "multilink"},
        "tires": {"front_size": "205/60R15", "rear_size": "205/60R15", "width_mm": 205, "aspect_ratio": 60, "wheel_diameter_in": 15},
        "aero": {"drag_coefficient": 0.33},
        "weight_kg": 1080, "weight_front_pct": 52,
        "fuel_type": "gasoline",
        "performance": {"0_100_km_h": 7.0, "top_speed_km_h": 215, "quarter_mile_s": 15.6, "lateral_g": 0.84},
        "price": {"min_usd": 3000, "max_usd": 30000, "avg_usd": 12000, "note": "CA18DET turbo; SR20DET in later S13"},
        "eras": "80s,90s", "tags": "jdm,drift,classic,turbo,affordable",
        "confidence": 0.85, "source": "reference"
    },
    # Nissan Silvia S14 (1993-1999)
    {
        "make": "Nissan", "model": "Silvia S14 (Kouki)", "year": 1997,
        "trim": "Kouki",
        "body_type": "coupe",
        "dimensions": {
            "length": 4.50, "width": 1.73, "height": 1.31,
            "wheelbase": 2.52, "track_width": 1.48, "ground_clearance": 0.14,
            "front_track_m": 1.48, "rear_track_m": 1.48,
            "front_overhang_m": 0.90, "rear_overhang_m": 1.08,
        },
        "engine": {
            "displacement_l": 2.0, "cylinders": 4, "configuration": "I4",
            "aspiration": "turbo", "power_hp": 220, "torque_nm": 275,
            "max_rpm": 7000, "idle_rpm": 800, "compression_ratio": 8.5,
            "bore_mm": 86.0, "stroke_mm": 86.0, "valves_per_cylinder": 4,
            "fuel_delivery": "MPI", "boost_bar": 0.7,
        },
        "drivetrain": "rwd",
        "transmission": {"gear_count": 5, "type": "manual", "final_drive": 3.69},
        "brakes": {"front_type": "ventilated_disc", "rear_type": "ventilated_disc", "front_diameter_mm": 280},
        "suspension": {"front_type": "macpherson", "rear_type": "multilink"},
        "tires": {"front_size": "205/55R16", "rear_size": "205/55R16", "width_mm": 205, "aspect_ratio": 55, "wheel_diameter_in": 16},
        "aero": {"drag_coefficient": 0.32},
        "weight_kg": 1240, "weight_front_pct": 52,
        "fuel_type": "gasoline",
        "performance": {"0_100_km_h": 6.0, "top_speed_km_h": 235, "quarter_mile_s": 14.8, "lateral_g": 0.89},
        "price": {"min_usd": 5000, "max_usd": 35000, "avg_usd": 15000, "note": "SR20DET, JDM spec"},
        "eras": "90s,2000s", "tags": "jdm,drift,turbo,classic",
        "confidence": 0.85, "source": "reference"
    },
    # Nissan Silvia S15 (1999-2002)
    {
        "make": "Nissan", "model": "Silvia S15 Spec R", "year": 2002,
        "trim": "Spec R",
        "body_type": "coupe",
        "dimensions": {
            "length": 4.44, "width": 1.73, "height": 1.32,
            "wheelbase": 2.52, "track_width": 1.48, "ground_clearance": 0.14,
            "front_track_m": 1.48, "rear_track_m": 1.48,
            "front_overhang_m": 0.88, "rear_overhang_m": 1.04,
        },
        "engine": {
            "displacement_l": 2.0, "cylinders": 4, "configuration": "I4",
            "aspiration": "turbo", "power_hp": 247, "torque_nm": 275,
            "max_rpm": 7200, "idle_rpm": 800, "compression_ratio": 8.5,
            "bore_mm": 86.0, "stroke_mm": 86.0, "valves_per_cylinder": 4,
            "fuel_delivery": "DI", "boost_bar": 0.85,
        },
        "drivetrain": "rwd",
        "transmission": {"gear_count": 6, "type": "manual", "final_drive": 3.69},
        "brakes": {"front_type": "ventilated_disc", "rear_type": "ventilated_disc", "front_diameter_mm": 296, "abs": True},
        "suspension": {"front_type": "macpherson", "rear_type": "multilink"},
        "tires": {"front_size": "225/45R17", "rear_size": "245/40R17", "width_mm": 225, "aspect_ratio": 45, "wheel_diameter_in": 17},
        "aero": {"drag_coefficient": 0.30},
        "weight_kg": 1240, "weight_front_pct": 53,
        "fuel_type": "gasoline",
        "performance": {"0_100_km_h": 5.4, "top_speed_km_h": 245, "quarter_mile_s": 13.9, "lateral_g": 0.96},
        "price": {"min_usd": 10000, "max_usd": 50000, "avg_usd": 25000, "note": "SR20DET, JDM only"},
        "eras": "2000s", "tags": "jdm,drift,turbo,legend,handling",
        "confidence": 0.85, "source": "reference"
    },
    # BMW M3 E30 (1986-1991)
    {
        "make": "BMW", "model": "M3 E30", "year": 1989,
        "trim": "",
        "body_type": "coupe",
        "dimensions": {
            "length": 4.33, "width": 1.68, "height": 1.37,
            "wheelbase": 2.57, "track_width": 1.41, "ground_clearance": 0.13,
            "front_track_m": 1.41, "rear_track_m": 1.42,
            "front_overhang_m": 0.80, "rear_overhang_m": 0.96,
        },
        "engine": {
            "displacement_l": 2.3, "cylinders": 4, "configuration": "I4",
            "aspiration": "NA", "power_hp": 200, "torque_nm": 240,
            "max_rpm": 7000, "idle_rpm": 900, "compression_ratio": 10.5,
            "bore_mm": 93.4, "stroke_mm": 84.0, "valves_per_cylinder": 4,
            "fuel_delivery": "MPI",
        },
        "drivetrain": "rwd",
        "transmission": {"gear_count": 5, "type": "manual", "final_drive": 3.15},
        "brakes": {"front_type": "ventilated_disc", "rear_type": "ventilated_disc", "front_diameter_mm": 282, "abs": False},
        "suspension": {"front_type": "macpherson", "rear_type": "semi_trailing_arm"},
        "tires": {"front_size": "205/55R15", "rear_size": "205/55R15", "width_mm": 205, "aspect_ratio": 55, "wheel_diameter_in": 15},
        "aero": {"drag_coefficient": 0.35},
        "weight_kg": 1200, "weight_front_pct": 54,
        "fuel_type": "gasoline",
        "performance": {"0_100_km_h": 6.7, "top_speed_km_h": 235, "quarter_mile_s": 15.1, "lateral_g": 0.90},
        "price": {"min_usd": 30000, "max_usd": 150000, "avg_usd": 65000, "note": "S14 engine, collector car"},
        "eras": "80s,90s", "tags": "classic,bmw,homologation,legend,collector",
        "confidence": 0.9, "source": "reference"
    },
    # BMW M3 E36 (1992-1999)
    {
        "make": "BMW", "model": "M3 E36", "year": 1996,
        "trim": "Euro",
        "body_type": "coupe",
        "dimensions": {
            "length": 4.43, "width": 1.71, "height": 1.35,
            "wheelbase": 2.70, "track_width": 1.43, "ground_clearance": 0.12,
            "front_track_m": 1.43, "rear_track_m": 1.44,
            "front_overhang_m": 0.80, "rear_overhang_m": 0.93,
        },
        "engine": {
            "displacement_l": 3.2, "cylinders": 6, "configuration": "I6",
            "aspiration": "NA", "power_hp": 321, "torque_nm": 350,
            "max_rpm": 7000, "idle_rpm": 800, "compression_ratio": 10.5,
            "bore_mm": 86.0, "stroke_mm": 91.0, "valves_per_cylinder": 4,
            "fuel_delivery": "MPI",
        },
        "drivetrain": "rwd",
        "transmission": {"gear_count": 5, "type": "manual", "final_drive": 3.23},
        "brakes": {"front_type": "ventilated_disc", "rear_type": "ventilated_disc", "front_diameter_mm": 315, "abs": True},
        "suspension": {"front_type": "macpherson", "rear_type": "z_axle"},
        "tires": {"front_size": "225/45R17", "rear_size": "245/40R17", "width_mm": 225, "aspect_ratio": 45, "wheel_diameter_in": 17},
        "aero": {"drag_coefficient": 0.32},
        "weight_kg": 1460, "weight_front_pct": 54,
        "fuel_type": "gasoline",
        "performance": {"0_100_km_h": 5.5, "top_speed_km_h": 250, "quarter_mile_s": 13.7, "lateral_g": 0.92},
        "price": {"min_usd": 5000, "max_usd": 30000, "avg_usd": 15000, "note": "US-spec 240hp; Euro 321hp shown here"},
        "eras": "90s", "tags": "classic,bmw,straight_six,affordable",
        "confidence": 0.85, "source": "reference"
    },
    # BMW M3 E46 (2000-2006)
    {
        "make": "BMW", "model": "M3 E46", "year": 2003,
        "trim": "CSL",
        "body_type": "coupe",
        "dimensions": {
            "length": 4.57, "width": 1.78, "height": 1.37,
            "wheelbase": 2.76, "track_width": 1.51, "ground_clearance": 0.11,
            "front_track_m": 1.51, "rear_track_m": 1.51,
            "front_overhang_m": 0.82, "rear_overhang_m": 0.99,
        },
        "engine": {
            "displacement_l": 3.2, "cylinders": 6, "configuration": "I6",
            "aspiration": "NA", "power_hp": 343, "torque_nm": 365,
            "max_rpm": 7900, "idle_rpm": 800, "compression_ratio": 11.5,
            "bore_mm": 87.0, "stroke_mm": 89.6, "valves_per_cylinder": 4,
            "fuel_delivery": "DI",
        },
        "drivetrain": "rwd",
        "transmission": {"gear_count": 6, "type": "manual", "final_drive": 3.62},
        "brakes": {"front_type": "ventilated_disc", "rear_type": "ventilated_disc", "front_diameter_mm": 345, "abs": True},
        "suspension": {"front_type": "macpherson", "rear_type": "multilink"},
        "tires": {"front_size": "225/40R19", "rear_size": "255/35R19", "width_mm": 225, "aspect_ratio": 40, "wheel_diameter_in": 19},
        "aero": {"drag_coefficient": 0.35, "downforce_kg": 35},
        "weight_kg": 1570, "weight_front_pct": 53,
        "fuel_type": "gasoline",
        "performance": {"0_100_km_h": 4.8, "top_speed_km_h": 250, "quarter_mile_s": 13.0, "lateral_g": 0.99},
        "price": {"min_usd": 8000, "max_usd": 50000, "avg_usd": 25000, "note": "S54 engine, SMG or manual"},
        "eras": "2000s", "tags": "classic,bmw,legend,handling,straight_six",
        "confidence": 0.9, "source": "reference"
    },
]


def reference_source(search=None, dry_run=False):
    """Return hardcoded reference cars, optionally filtered."""
    cars = REFERENCE_CARS
    if search:
        q = search.lower()
        cars = [c for c in cars if q in f"{c['make']} {c['model']}".lower()]
    return cars
